spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nikhilsingh-0/configserver.git
          username: nikhilsingh-0
          password: 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

server:
  port: 8888